### ISSUE TITLE
How to use loaded entity data

### ISSUE THREAD

**Issue by tarlepp** [matthiasnoback/symfony-console-form#16]
Hi, I'm trying to make user create and edit console command with this bundle.

I have managed to make create part to work as it should, but within edit action I have problem within ArrayCollection type on my user entity.

Below is how I'm currently trying to use that form

```
$user = $formHelper->interactUsingForm('App\Form\Console\User', $this->input, $this->output, ['data' => $user]);
```

where `$user` is loaded User entity from database. All work with normal inputs, but when the form is processing many-to-many relation (userGroups) I get following error:

```


  [Symfony\Component\Debug\Exception\ContextErrorException]                                                  
  Catchable Fatal Error: Object of class Doctrine\ORM\PersistentCollection could not be converted to string  


Exception trace:
 () at /home/wunder/projects/symfony-backend/vendor/matthiasnoback/symfony-console-form/src/Console/Formatter/Format.php:30
 Symfony\Component\Debug\ErrorHandler->handleError() at n/a:n/a
 strtr() at /home/wunder/projects/symfony-backend/vendor/matthiasnoback/symfony-console-form/src/Console/Formatter/Format.php:30
 Matthias\SymfonyConsoleForm\Console\Formatter\Format::forQuestion() at /home/wunder/projects/symfony-backend/vendor/matthiasnoback/symfony-console-form/src/Bridge/Transformer/AbstractTransformer.php:44
 Matthias\SymfonyConsoleForm\Bridge\Transformer\AbstractTransformer->formattedQuestion() at /home/wunder/projects/symfony-backend/vendor/matthiasnoback/symfony-console-form/src/Bridge/Transformer/AbstractTransformer.php:23
 Matthias\SymfonyConsoleForm\Bridge\Transformer\AbstractTransformer->questionFrom() at /home/wunder/projects/symfony-backend/vendor/matthiasnoback/symfony-console-form/src/Bridge/Transformer/ChoiceTransformer.php:20
 Matthias\SymfonyConsoleForm\Bridge\Transformer\ChoiceTransformer->transform() at /home/wunder/projects/symfony-backend/vendor/matthiasnoback/symfony-console-form/src/Bridge/Interaction/FieldInteractor.php:48
 Matthias\SymfonyConsoleForm\Bridge\Interaction\FieldInteractor->interactWith() at /home/wunder/projects/symfony-backend/vendor/matthiasnoback/symfony-console-form/src/Bridge/Interaction/DelegatingInteractor.php:42
 Matthias\SymfonyConsoleForm\Bridge\Interaction\DelegatingInteractor->interactWith() at /home/wunder/projects/symfony-backend/vendor/matthiasnoback/symfony-console-form/src/Bridge/Interaction/CompoundInteractor.php:56
 Matthias\SymfonyConsoleForm\Bridge\Interaction\CompoundInteractor->interactWith() at /home/wunder/projects/symfony-backend/vendor/matthiasnoback/symfony-console-form/src/Bridge/Interaction/DelegatingInteractor.php:42
 Matthias\SymfonyConsoleForm\Bridge\Interaction\DelegatingInteractor->interactWith() at /home/wunder/projects/symfony-backend/vendor/matthiasnoback/symfony-console-form/src/Console/Helper/FormHelper.php:49
 Matthias\SymfonyConsoleForm\Console\Helper\FormHelper->interactUsingForm() at /home/wunder/projects/symfony-backend/src/App/Command/User/EditUserCommand.php:74
 App\Command\User\EditUserCommand->execute() at /home/wunder/projects/symfony-backend/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /home/wunder/projects/symfony-backend/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:807
 Symfony\Component\Console\Application->doRunCommand() at /home/wunder/projects/symfony-backend/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:186
 Symfony\Component\Console\Application->doRun() at /home/wunder/projects/symfony-backend/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/wunder/projects/symfony-backend/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:117
 Symfony\Component\Console\Application->run() at /home/wunder/projects/symfony-backend/bin/console:29
```

And below is my User form definition

```
<?php
namespace App\Form\Console;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class User extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'username',
                Type\TextType::class,
                [
                    'label'     => 'Username',
                    'required'  => true,
                ]
            )
            ->add(
                'firstname',
                Type\TextType::class,
                [
                    'label'     => 'Firstname',
                    'required'  => true,
                ]
            )
            ->add(
                'surname',
                Type\TextType::class,
                [
                    'label'     => 'Surname',
                    'required'  => true,
                ]
            )
            ->add(
                'email',
                Type\EmailType::class,
                [
                    'label'     => 'Email address',
                    'required'  => true,
                ]
            )
            ->add(
                'userGroups',
                EntityType::class,
                [
                    'label'     => 'User group(s)',
                    'required'  => true,
                    'class'     => 'App\Entity\UserGroup',
                    'multiple'  => true,
                    'choice_label' => function(/** @var \App\Entity\UserGroup $group */$group) {
                        return $group->getName() . ' [' . $group->getRole() . ']';
                    },
                ]
            )
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => 'App\Entity\User'
        ]);
    }
}
```

And this form works when I'm creating a new user with different console command.

Any ideas how to make this work?

**Comment by tarlepp** [comment]
I also tried this with simplier ChoiceType form input.

``` php
->add(
    'userGroups',
    Type\ChoiceType::class,
    [
        'choices'   => $this->getUserGroupChoices(),
        'multiple'  => true,
    ]
)
```

Where 'choices' are just plain old array:

``` php
Array
(
    [Admin [ROLE_ADMIN]] => 3
    [Root Users [ROLE_SUPER_ADMIN]] => 4
    [User [ROLE_USER]] => 6
)
```

Once again create of new item via this form works like it should, but when I'm trying to implement edit behaviour it will cause the same error.

**Comment by matthiasnoback** [comment]
I'm sorry, I don't know what's going on by just reading the text. Could you create a pull request which demonstrates the problem? I'm happy to come up with a fix then :)

**Comment by tarlepp** [comment]
Made simple PR to point the problem out.

**Comment by matthiasnoback** [comment]
I'll check it out - no promises about the delivery time though :)

**Comment by matthiasnoback** [comment]
Okay, I checked it out. Waiting for Travis now.

**Comment by matthiasnoback** [comment]
Meaning - I have a fix for the multiselect form you created. You will have to check out if it also works with your entity situation.

**Comment by matthiasnoback** [comment]
I released a new patch version just now. Could you please check if it works correctly in your situation? If it doesn't, please open a new PR with a (minimal) situation that causes failure.

**Comment by tarlepp** [comment]
It seems to work as expected with plain key - value pairs now, thanks for that!

Although actual entity usage is still a problem here, yet although users should use DTO's for those forms but still...

**Comment by matthiasnoback** [comment]
Thanks for looking into it. Does the problem have anything to do with ArrayCollection stuff? Because if it's about __toString(), there's no (generic) way to circumvent that I guess.
