### ISSUE TITLE
ChoiceType fails

### ISSUE THREAD

**Issue by craigh** [matthiasnoback/symfony-console-form#6]
I am struggling to get a ChoiceType field with a custom validator to work properly from the command line. **It works correct via http.**

[form field](https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreInstallerBundle/Form/Type/DbCredsType.php#L30-L34)

[callback](https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreInstallerBundle/Form/Type/DbCredsType.php#L102)

[validator](https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreInstallerBundle/Validator/CoreInstallerValidator.php#L27-L53)

I added a `var_dump($object);` [before line 50](https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreInstallerBundle/Validator/CoreInstallerValidator.php#L50) in the validator
![screen shot 2015-06-10 at 7 16 17 pm](https://cloud.githubusercontent.com/assets/350048/8096445/368ee6a4-0fa5-11e5-8195-2b536bddea15.png)

So, it is apparent that the form is not passing the values from the choice fields to the validator properly. It is also not recognizing the default value. (These are not yet Symfony 2.7/3.0 - type forms, but I did try to fix that to see if there was any effect and found none).

I wondered if there was something wrong with my form because choice fields in other forms seems to work ok. Can you spot any problems?

**Comment by matthiasnoback** [comment]
Sorry, I don't know what could be the problem!

**Comment by cmfcmf** [comment]
After further elaboration, the issue seems to be in the `RawChoiceQuestion` class. I added the following debug statements:

``` php
<?php

namespace Matthias\SymfonyConsoleForm\Console\Helper\Question;

use Symfony\Component\Console\Question\ChoiceQuestion;

/**
 * Inherits default behavior of ChoiceQuestion, but returns the value of a choice instead of its label
 */
class RawChoiceQuestion extends ChoiceQuestion
{
    public function getValidator()
    {
        $originalValidator = parent::getValidator();
        return function ($selected) use ($originalValidator) {
            echo "SEL: " . $selected . PHP_EOL;
            $value = $originalValidator($selected);
            echo "VAL: " . $value . PHP_EOL;
            $choices = array_flip($this->getChoices());
            echo "FLIPPED CHOICES: "; var_dump($choices);
            if (is_array($value)) {
                return array_intersect_key($choices, $value);
            } else {
                return $choices[$value];
            }
        };
    }
}
```

This results in:

```
Select your default language [en]:
  [en] English
 >
SEL: en
VAL: en
FLIPPED CHOICES: array(1) {
  'English' =>
  string(2) "en"
}

Notice: Undefined index: en in E:\xampp\htdocs\tmp\Zikula_Core-1.4.0\vendor\matt
hiasnoback\symfony-console-form\src\Console\Helper\Question\RawChoiceQuestion.ph
p on line 24
```

It seems like all the flipping is not necessary because the value is already correctly returned. 

(this is the form: https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreInstallerBundle/Form/Type/LocaleType.php#L29-L30 [where `getInstalledLanguageNames()` returns something like `['en' => 'English']` and `getLanguageCode()` returns `en`])

### It works when I just do `return $value`.

**Comment by craigh** [comment]
That is a different form than the one I was working with in the OP. but they are in sequence (the LocaleType is first). they both employ a ChoiceType field. LocaleType doesn't use a custom validator.

**Comment by craigh** [comment]
FYI - we are using Symfony 2.7 but the forms are 2.6-type choice forms (e.g. non-flipped choice arrays - relating to [second bullet here](https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.7.md#form)) perhaps you were using a 2.7+ dev setup in your development?

**Comment by matthiasnoback** [comment]
Could you please add a failing test case for this? That way we can isolate the problem and you or I could start working on a fix.

**Comment by craigh** [comment]
yes we can probably do that, but I noticed there is not a passing test case for ChoiceType in your tests.

**Comment by matthiasnoback** [comment]
No, that's right. But just a failing test would suffice in this case (I didn't write unit tests, right? ;))

**Comment by craigh** [comment]
@matthiasnoback I have created a small Bundle that demonstrates the failure

https://github.com/craigh/FormChoiceBundle

please forgive me as I do not know how to write unit tests :smile:

/cc @cmfcmf

**Comment by craigh** [comment]
I updated the Bundle with improvements in the test and found some good information

**Comment by matthiasnoback** [comment]
Thanks, I'll take a look at this soon.

## 

_Noback's Office_
http://nobacksoffice.nl
+31(0)614995363

**Comment by matthiasnoback** [comment]
I've been trying to find out what's going on but I'm a bit stuck here. Will try to find some time later, although I'm also working on other things right now, so no promises...

**Comment by matthiasnoback** [comment]
Ah, hehe, I'm "git commit --amend"-ing my way into a proper fix for this... I've added Travis configuration as well to make sure that the library works for Symfony 2.5 as well as 2.7. This should be fixed soon!

**Comment by matthiasnoback** [comment]
Please update to `v1.0.1` - let's hope this is fixed now!

**Comment by craigh** [comment]
:( this is still failing using my bundle. The first question is a ["3.0-type" question](https://github.com/craigh/FormChoiceBundle/blob/master/Form/Type/ColorType.php#L14-L22)

![screen shot 2015-06-20 at 7 54 47 am](https://cloud.githubusercontent.com/assets/350048/8267104/ad6d1d76-1721-11e5-8b8a-d596300051e4.png)
- first answer using default
- second answer typing "blue"
- third answer typing "Blue color" (which it "auto-types")

**Comment by craigh** [comment]
If I change the test to only use the ["2.6"-type question](https://github.com/craigh/FormChoiceBundle/blob/master/Form/Type/LocaleType.php#L14-L21) then it works as expected.
![screen shot 2015-06-20 at 8 01 00 am](https://cloud.githubusercontent.com/assets/350048/8267119/86e82ef6-1722-11e5-8969-6f3ed1099508.png)

**Comment by craigh** [comment]
summary: old way works correctly now. new way still failing.

**Comment by matthiasnoback** [comment]
Ah, right. I didn't test the new way of defining choice fields. Will see if
I can do that.
Op 20 jun. 2015 14:03 schreef "Craig Heydenburg" notifications@github.com:

**Comment by matthiasnoback** [comment]
After hours and hours of trying the best options here, I fixed it. Just update to v1.0.2. The problem is that this library shouldn't rely on the strange implementation of `ChoiceQuestion` from the Console component. Instead, I have provided my own implementation for it, which always returns the value of a choice, never its data or label. So now it works in all scenarios. If it doesn't, just let me know!

**Comment by craigh** [comment]
first - THANKS AGAIN! for continuing to work on this and try to solve the problems with us :smile: 

Hi - I am testing just now with my bundle. The current state has the Sym-3.0 ChoiceType form commented out. I have re-enabled that portion for my testing here.

**Most** everything works  :white_check_mark: 
the Sym-2.6-type forms work as expected and the [repeated](https://github.com/matthiasnoback/symfony-console-form/issues/7) field works and also in `-n`

unfortunately, **in the Sym-3.0-ChoiceType Form** the use of the default value and any of the original 'values' of the choice array do not work.
![screen shot 2015-06-24 at 11 09 27 am](https://cloud.githubusercontent.com/assets/350048/8333602/c89b7a96-1a61-11e5-9d28-13d73ebbe476.png)

In the screenshot here, you can see that 'blue' is provided as the default value for the choice. (this is set in the Form).
- choosing the default by simply hitting enter **fails**. :x: 
- choosing the default by typing the default value **fails**. :x: 
- typing the numeric value (not shown) **succeeds**.  :white_check_mark: 
- typing the displayed value (e.g. `Blue color`) **succeeds**.  :white_check_mark: 
- other values (e.g. `red`, `yellow`) also **fail** (not shown) :x:

additionally, entering an appropriate value in **non-interactive mode** for the color field (Sym-3.0 type) requires the numeric key.
![screen shot 2015-06-24 at 11 18 51 am](https://cloud.githubusercontent.com/assets/350048/8333858/d48fc4a0-1a62-11e5-8a1c-81d9a8d76a78.png)

## SUMMARY

The default value for the Sym-3.0-type forms and the value keys are still a problem.

## FTR:

``` shell
[Craigs-iMac2013:MAMP/htdocs/my_project] craig% composer show -i
...
matthiasnoback/symfony-console-form  v1.0.2  Use Symfony forms for Console command input
...
```

**Comment by matthiasnoback** [comment]
Thanks for testing! This is valuable feedback. Yes, we should add support for inputting the actual data as well. I hope I have time for this next week. I'm starting to like this bughunt/fixing party :)

**Comment by matthiasnoback** [comment]
@craigh So I fixed this :)
I decided to allow value, data and label of a choice field to be used as valid input.

**Comment by craigh** [comment]
hi!

I tried to test and have the following error:

``` shell
php app/console form:choice:test

Fatal error: Call to undefined function Assert\that() in /Applications/MAMP/htdocs/my_project/vendor/matthiasnoback/symfony-console-form/src/Console/Helper/Question/AlwaysReturnKeyOfChoiceQuestion.php on line 20

Call Stack:
    0.0003     235824   1. {main}() /Applications/MAMP/htdocs/my_project/app/console:0
    0.0393    3216592   2. Symfony\Component\Console\Application->run() /Applications/MAMP/htdocs/my_project/app/console:27
    0.0441    3419648   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Applications/MAMP/htdocs/my_project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
    0.1856   10493904   4. Symfony\Component\Console\Application->doRun() /Applications/MAMP/htdocs/my_project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
    0.1859   10494824   5. Symfony\Component\Console\Application->doRunCommand() /Applications/MAMP/htdocs/my_project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:195
    0.2115   11252272   6. Symfony\Component\Console\Command\Command->run() /Applications/MAMP/htdocs/my_project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:886
    0.2119   11257152   7. FormChoiceBundle\Command\ChoiceTestCommand->execute() /Applications/MAMP/htdocs/my_project/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
    0.2188   11286552   8. Matthias\SymfonyConsoleForm\Console\Helper\FormHelper->interactUsingForm() /Applications/MAMP/htdocs/my_project/src/FormChoiceBundle/Command/ChoiceTestCommand.php:35
    0.8133   15047920   9. Matthias\SymfonyConsoleForm\Bridge\Interaction\DelegatingInteractor->interactWith() /Applications/MAMP/htdocs/my_project/vendor/matthiasnoback/symfony-console-form/src/Console/Helper/FormHelper.php:34
    0.8145   15090200  10. Matthias\SymfonyConsoleForm\Bridge\Interaction\CompoundInteractor->interactWith() /Applications/MAMP/htdocs/my_project/vendor/matthiasnoback/symfony-console-form/src/Bridge/Interaction/DelegatingInteractor.php:29
    0.8145   15090832  11. Matthias\SymfonyConsoleForm\Bridge\Interaction\DelegatingInteractor->interactWith() /Applications/MAMP/htdocs/my_project/vendor/matthiasnoback/symfony-console-form/src/Bridge/Interaction/CompoundInteractor.php:40
    0.8151   15116336  12. Matthias\SymfonyConsoleForm\Bridge\Interaction\FieldInteractor->interactWith() /Applications/MAMP/htdocs/my_project/vendor/matthiasnoback/symfony-console-form/src/Bridge/Interaction/DelegatingInteractor.php:29
    0.8152   15116568  13. Matthias\SymfonyConsoleForm\Bridge\Transformer\ChoiceTransformer->transform() /Applications/MAMP/htdocs/my_project/vendor/matthiasnoback/symfony-console-form/src/Bridge/Interaction/FieldInteractor.php:32
    0.8472   15355088  14. Matthias\SymfonyConsoleForm\Console\Helper\Question\AlwaysReturnKeyOfChoiceQuestion->__construct() /Applications/MAMP/htdocs/my_project/vendor/matthiasnoback/symfony-console-form/src/Bridge/Transformer/ChoiceTransformer.php:14

[2015-07-03 16:57:53] php.CRITICAL: Fatal Error: Call to undefined function Assert\that() {"type":1,"file":"/Applications/MAMP/htdocs/my_project/vendor/matthiasnoback/symfony-console-form/src/Console/Helper/Question/AlwaysReturnKeyOfChoiceQuestion.php","line":20,"level":-1,"stack":[{"function":"__construct","type":"->","class":"Matthias\\SymfonyConsoleForm\\Console\\Helper\\Question\\AlwaysReturnKeyOfChoiceQuestion","file":"/Applications/MAMP/htdocs/my_project/vendor/matthiasnoback/symfony-console-form/src/Bridge/Transformer/ChoiceTransformer.php","line":14,"args":[]},{"function":"transform","type":"->","class":"Matthias\\SymfonyConsoleForm\\Bridge\\Transformer\\ChoiceTransformer","file":"/Applications/MAMP/htdocs/my_project/vendor/matthiasnoback/symfony-console-form/src/Bridge/Interaction/FieldInteractor.php","line":32,"args":[]},{"function":"interactWith","type":"->","class":"Matthias\\SymfonyConsoleForm\\Bridge\\Interaction\\FieldInteractor","file":"/Applications/MAMP/htdocs/my_project/vendor/matthiasnoback/symfony-console-form/src/Bridge/Interaction/DelegatingInteractor.php","line":29,"args":[]},{"function":"interactWith","type":"->","class":"Matthias\\SymfonyConsoleForm\\Bridge\\Interaction\\DelegatingInteractor","file":"/Applications/MAMP/htdocs/my_project/vendor/matthiasnoback/symfony-console-form/src/Bridge/Interaction/CompoundInteractor.php","line":40,"args":[]},{"function":"interactWith","type":"->","class":"Matthias\\SymfonyConsoleForm\\Bridge\\Interaction\\CompoundInteractor","file":"/Applications/MAMP/htdocs/my_project/vendor/matthiasnoback/symfony-console-form/src/Bridge/Interaction/DelegatingInteractor.php","line":29,"args":[]},{"function":"interactWith","type":"->","class":"Matthias\\SymfonyConsoleForm\\Bridge\\Interaction\\DelegatingInteractor","file":"/Applications/MAMP/htdocs/my_project/vendor/matthiasnoback/symfony-console-form/src/Console/Helper/FormHelper.php","line":34,"args":[]},{"function":"interactUsingForm","type":"->","class":"Matthias\\SymfonyConsoleForm\\Console\\Helper\\FormHelper","file":"/Applications/MAMP/htdocs/my_project/src/FormChoiceBundle/Command/ChoiceTestCommand.php","line":35,"args":[]},{"function":"execute","type":"->","class":"FormChoiceBundle\\Command\\ChoiceTestCommand","file":"/Applications/MAMP/htdocs/my_project/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php","line":259,"args":[]},{"function":"run","type":"->","class":"Symfony\\Component\\Console\\Command\\Command","file":"/Applications/MAMP/htdocs/my_project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php","line":886,"args":[]},{"function":"doRunCommand","type":"->","class":"Symfony\\Component\\Console\\Application","file":"/Applications/MAMP/htdocs/my_project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php","line":195,"args":[]},{"function":"doRun","type":"->","class":"Symfony\\Component\\Console\\Application","file":"/Applications/MAMP/htdocs/my_project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php","line":96,"args":[]},{"function":"doRun","type":"->","class":"Symfony\\Bundle\\FrameworkBundle\\Console\\Application","file":"/Applications/MAMP/htdocs/my_project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php","line":126,"args":[]},{"function":"run","type":"->","class":"Symfony\\Component\\Console\\Application","file":"/Applications/MAMP/htdocs/my_project/app/console","line":27,"args":[]},{"function":"{main}","file":"/Applications/MAMP/htdocs/my_project/app/console","line":0,"args":[]}]} 



  [Symfony\Component\Debug\Exception\UndefinedFunctionException]  
  Attempted to call function "that" from namespace "Assert".      



form:choice:test [--color [COLOR]] [--locale [LOCALE]] [--password [PASSWORD]]
```

**Comment by matthiasnoback** [comment]
Oops, sorry about that! I used a function that was only installed as a dev dependency. I just fixed it and released v1.1.1.

**Comment by craigh** [comment]
I was finally able to test this with your new changes and it seems to work as expected! great work :+1:

**Comment by matthiasnoback** [comment]
Oh, that's great, thanks.
